"""User accounts + Argon2id password hashing — PostgreSQL only.

Auth lives in the `auth` schema (see schema_auth.sql). Registration is restricted
to the allowed email domains; passwords are hashed with Argon2id via argon2-cffi
using the library's recommended parameters (never hand-rolled, never plaintext,
never returned through the public API). Email uniqueness is case-insensitive.

Pure helpers (domain validation, hashing/verification) have no DB dependency and
are unit-tested directly; the DB helpers require the Postgres backend.
"""
from __future__ import annotations

import os
import re
from typing import Optional

from .backend import db

_IS_PG = db.__name__.endswith("db_pg")

ALLOWED_DOMAINS = ("defra.gov.uk", "equalexperts.com")
DOMAIN_REJECT_MESSAGE = "Please use your DEFRA or Equal Experts email address."
ROLES = ("Admin", "Team Manager", "User", "Tester")
STATUSES = ("pending", "active", "disabled")
MIN_PASSWORD_LEN = 8

_SCHEMA_PATH = os.path.join(os.path.dirname(__file__), "schema_auth.sql")
_EMAIL_RE = re.compile(r"^[^@\s]+@[^@\s]+\.[^@\s]+$")

# Columns safe to return through the app/API — never includes password_hash.
_PUBLIC_COLS = ("id, email, first_name, last_name, role, account_status, "
                "email_verified_at, failed_login_count, locked_until, "
                "created_at, updated_at, last_login_at")


class EmailTakenError(Exception):
    """Raised when an account already exists for the (case-insensitive) email."""


def _require_pg() -> None:
    if not _IS_PG:
        raise RuntimeError("accounts requires the Postgres backend — auth is Postgres-only.")


# ---- pure helpers (no DB) -------------------------------------------------

def normalise_email(email: Optional[str]) -> str:
    return (email or "").strip().lower()


def email_domain_allowed(email: Optional[str]) -> bool:
    """True only for a well-formed address on an allowed domain (case-insensitive)."""
    e = normalise_email(email)
    if not _EMAIL_RE.match(e):
        return False
    return e.rsplit("@", 1)[-1] in ALLOWED_DOMAINS


def _hasher():
    from argon2 import PasswordHasher       # argon2-cffi; recommended defaults
    return PasswordHasher()


def hash_password(password: str) -> str:
    """Argon2id hash (unique salt generated by the library)."""
    return _hasher().hash(password)


def verify_password(password_hash: str, password: str) -> bool:
    from argon2 import PasswordHasher
    from argon2.exceptions import Argon2Error
    try:
        return PasswordHasher().verify(password_hash, password)
    except (Argon2Error, ValueError, TypeError):
        return False


def needs_rehash(password_hash: str) -> bool:
    """True if the stored hash used weaker-than-current parameters (rehash on next login)."""
    try:
        return _hasher().check_needs_rehash(password_hash)
    except Exception:
        return True


# ---- DB helpers (Postgres) ------------------------------------------------

def init_auth_schema(conn) -> None:
    """Create the auth schema + tables (idempotent). Applied at deploy/startup."""
    _require_pg()
    with open(_SCHEMA_PATH, encoding="utf-8") as fh:
        conn.execute(fh.read())
    conn.commit()


def create_user(conn, *, email: str, first_name: str, last_name: str, password: str,
                role: str = "User", account_status: str = "active") -> dict:
    """Create an account. `role`/`account_status` are explicit arguments (never taken
    from request data) to prevent mass-assignment. Returns the public row (no hash).
    Raises ValueError for validation problems, EmailTakenError for a duplicate email."""
    _require_pg()
    e = normalise_email(email)
    if not email_domain_allowed(e):
        raise ValueError(DOMAIN_REJECT_MESSAGE)
    if role not in ROLES:
        raise ValueError("invalid role")
    if account_status not in STATUSES:
        raise ValueError("invalid account status")
    if not (first_name or "").strip() or not (last_name or "").strip():
        raise ValueError("First and last name are required.")
    if not password or len(password) < MIN_PASSWORD_LEN:
        raise ValueError(f"Password must be at least {MIN_PASSWORD_LEN} characters.")
    pw = hash_password(password)
    try:
        row = conn.execute(
            f"INSERT INTO auth.users (email, first_name, last_name, password_hash, role, account_status) "
            f"VALUES (%s, %s, %s, %s, %s, %s) RETURNING {_PUBLIC_COLS}",
            (e, first_name.strip(), last_name.strip(), pw, role, account_status)).fetchone()
        conn.commit()
        return dict(row)
    except Exception as exc:                    # unique-violation on lower(email)
        conn.rollback()
        if "users_email_lower_uniq" in str(exc) or "unique" in str(exc).lower():
            raise EmailTakenError(e) from None
        raise


def get_user_by_email(conn, email: str, *, with_hash: bool = False) -> Optional[dict]:
    """Fetch a user by case-insensitive email. `with_hash=True` (login only) also
    returns password_hash — never expose that to the client."""
    _require_pg()
    cols = _PUBLIC_COLS + (", password_hash" if with_hash else "")
    row = conn.execute(f"SELECT {cols} FROM auth.users WHERE lower(email) = lower(%s)",
                       (normalise_email(email),)).fetchone()
    return dict(row) if row else None


def get_user(conn, user_id: str, *, with_hash: bool = False) -> Optional[dict]:
    _require_pg()
    cols = _PUBLIC_COLS + (", password_hash" if with_hash else "")
    row = conn.execute(f"SELECT {cols} FROM auth.users WHERE id = %s", (user_id,)).fetchone()
    return dict(row) if row else None
